### ISSUE TITLE
create capacity to start publishing chain at the "Invite" stage

### ISSUE THREAD

**Issue by kellyhiser** [therabble/org.nashville.library.boombox#12]
There will be no call for submissions for at least the first crop of BB albums. So, the ideal process in MUSICat goes something like this:

Librarian invites an artist to submit their album to the collection
Artist receives email with a link to Complete Submission
and so on

We'll need some kind of "create submission" object at the jury or invite stage to do this.

**Comment by prestonaustin** [comment]
I'm going to assume this has to be a function in the invite stage,
otherwise confusing.

At the jury stage we'll also have a create-new function, so that curators
can have a "suggestion holding area" for suggested inclusions, but I think
that's just a modification of the existing submission-for-consideration
form, one where a suggestor is authoring a unilateral proxy submission for
a prospective invitee. I think that should involve modified fields to
surface different attributes of our artist/album schemata, he says, idly
wondering if that's really a valid usage of schemata, to make it easy and
intuitive to point curators to a suggested artists works online rather than
uploading them in a potentially infringing manner.

**Comment by kellyhiser** [comment]
Yes to the assumption that this begins at the invite stage. We'll assume librarians have contact information and the publishing chain will begin with an email to artists inviting them to Complete Submissions.

**Comment by kellyhiser** [comment]
done, available with next deploy.
